import React, { useState } from 'react';
import { Col, Container, Row } from "react-bootstrap";
import { Link } from "react-router-dom";
export default function Faqone () {
    const [activeIndex, setActiveIndex] = useState(null); 

    const toggleVisibility = (index) => {
      setActiveIndex(activeIndex === index ? null : index);
    };
    return (
        <>
        <section className="faq-one">
            <div className="bg"></div>
            <div className="icon"></div>
            <Container>
                <Row>
                <Col sm={12} md={12} lg={5} xl={5}>
                <div className="faq-title mb-5">
                    <h6>
                        Faq
                    </h6>
                    <h2 className="mt-3">Frequently asked <span><i>questions</i></span></h2>
                    <p>Lorem ipsum dolor sit amet consectetur adipiscing vitae mattis tellus. Nullam quis mattis ligula consectetur.</p>
                    <div className="cont-btn">
                    <Link to={"/"}>Contact now</Link>
                    </div>
                </div>
                </Col>
                <Col sm={12} md={12} lg={7} xl={7}>
                <div className="tool-dropdown">
      <div className="block">
        <h3 onClick={() => toggleVisibility(0)}>
          <a href="javascript:void(0)" className="fa-solid fa-plus"></a> How does your AI copywriting tool work?
        </h3>
        {activeIndex === 0 && (
          <p>Our AI copywriting tool uses sophisticated algorithms to understand context, tone, and language nuances...</p>
        )}
      </div>

      <div className="block">
        <h3 onClick={() => toggleVisibility(1)}>
          <a href="javascript:void(0)" className="fa-solid fa-plus"></a> What is AI copywriting?
        </h3>
        {activeIndex === 1 && (
          <p>AI copywriting uses advanced machine learning algorithms to produce content...</p>
        )}
      </div>

      <div className="block">
        <h3 onClick={() => toggleVisibility(2)}>
          <a href="javascript:void(0)" className="fa-solid fa-plus"></a> Can I trust the content generated by AI?
        </h3>
        {activeIndex === 2 && (
          <p>Yes, the AI produces content based on data analysis and understanding of language...</p>
        )}
      </div>

      <div className="block">
        <h3 onClick={() => toggleVisibility(3)}>
          <a href="javascript:void(0)" className="fa-solid fa-plus"></a> What types of content can your AI generate?
        </h3>
        {activeIndex === 3 && (
          <p>The AI can generate a variety of content types such as blog posts, social media copy, etc...</p>
        )}
      </div>

      <div className="block">
        <h3 onClick={() => toggleVisibility(4)}>
          <a href="javascript:void(0)" className="fa-solid fa-plus"></a> What languages does your AI support?
        </h3>
        {activeIndex === 4 && (
          <p>Our AI supports multiple languages including English, Spanish, French, and more...</p>
        )}
      </div>
    </div>
                </Col>
                </Row>
                </Container>     
                  </section>
        </>
    )
}